package coregamefiles;

public enum GameMapArtConditionEnum {

    //create enums to define map conditions in GameMapArtEngine
    MAP_ONE, MAP_TWO, MAP_THREE, MAP_FOUR, MAP_FIVE, MAP_SIX, MAP_SEVEN, MAP_EIGHT, MAP_NINE,
    MAP_TEN, MAP_ELEVEN, MAP_TWELVE, MAP_THIRTEEN, MAP_FOURTEEN, MAP_FIFTEEN, MAP_SIXTEEN,
    MAP_SEVENTEEN, MAP_EIGHTEEN, MAP_NINETEEN, MAP_TWENTY, MAP_TWENTY_ONE, MAP_TWENTY_TWO,
    MAP_TWENTY_THREE, MAP_TWENTY_FOUR, MAP_TWENTY_FIVE, MAP_TWENTY_SIX, MAP_TWENTY_SEVEN,
    MAP_TWENTY_EIGHT, MAP_TWENTY_NINE, MAP_THIRTY, MAP_THIRTY_ONE, MAP_THIRTY_TWO,
    MAP_THIRTY_THREE, MAP_THIRTY_FOUR, MAP_THIRTY_FIVE, MAP_THIRTY_SIEX, MAP_THIRTY_SEVEN,
    MAP_THIRTY_EIGHT, MAP_THIRTY_NINE, MAP_FORTY, MAP_FORTY_ONE, MAP_FORTY_TWO;
}